---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-deploy
  labels:
    app: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        ports:
          - containerPort: 5984
        env:
          - name: COUCHDB_USER
            value: admin
          - name: COUCHDB_PASSWORD
            value: password
---        
apiVersion: v1
kind: Service
metadata:
  name: couchdb-deploy
  labels:
    app: couchdb
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    app: couchdb

